# Generated by Django 4.2.2 on 2024-07-20 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('cell_id', models.AutoField(primary_key=True, serialize=False)),
                ('discharge_capacity', models.FloatField()),
                ('nominal_capacity', models.FloatField()),
            ],
            options={
                'db_table': 'cells',
            },
        ),
        migrations.CreateModel(
            name='CellData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('current_data', models.FloatField()),
                ('voltage_data', models.FloatField()),
                ('capacity_data', models.FloatField()),
                ('temperature_data', models.FloatField()),
                ('time_data', models.DateTimeField()),
                ('cell', models.ForeignKey(db_column='cell_id', on_delete=django.db.models.deletion.CASCADE, to='api.cell')),
            ],
            options={
                'db_table': 'cell_data',
            },
        ),
    ]
